/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as SeguidosRouteImport } from './routes/seguidos'
import { Route as RecomendacionesRouteImport } from './routes/recomendaciones'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as ArtistaIdRouteImport } from './routes/artista.$id'
import { Route as AlbumIdRouteImport } from './routes/album.$id'

const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguidosRoute = SeguidosRouteImport.update({
  id: '/seguidos',
  path: '/seguidos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendacionesRoute = RecomendacionesRouteImport.update({
  id: '/recomendaciones',
  path: '/recomendaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistaIdRoute = ArtistaIdRouteImport.update({
  id: '/artista/$id',
  path: '/artista/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/seguidos': typeof SeguidosRoute
  '/wrapped': typeof WrappedRoute
  '/album/$id': typeof AlbumIdRoute
  '/artista/$id': typeof ArtistaIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/seguidos': typeof SeguidosRoute
  '/wrapped': typeof WrappedRoute
  '/album/$id': typeof AlbumIdRoute
  '/artista/$id': typeof ArtistaIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/recomendaciones': typeof RecomendacionesRoute
  '/seguidos': typeof SeguidosRoute
  '/wrapped': typeof WrappedRoute
  '/album/$id': typeof AlbumIdRoute
  '/artista/$id': typeof ArtistaIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/buscar'
    | '/favoritos'
    | '/recomendaciones'
    | '/seguidos'
    | '/wrapped'
    | '/album/$id'
    | '/artista/$id'
    | '/playlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/buscar'
    | '/favoritos'
    | '/recomendaciones'
    | '/seguidos'
    | '/wrapped'
    | '/album/$id'
    | '/artista/$id'
    | '/playlist/$id'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/buscar'
    | '/favoritos'
    | '/recomendaciones'
    | '/seguidos'
    | '/wrapped'
    | '/album/$id'
    | '/artista/$id'
    | '/playlist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  BuscarRoute: typeof BuscarRoute
  FavoritosRoute: typeof FavoritosRoute
  RecomendacionesRoute: typeof RecomendacionesRoute
  SeguidosRoute: typeof SeguidosRoute
  WrappedRoute: typeof WrappedRoute
  AlbumIdRoute: typeof AlbumIdRoute
  ArtistaIdRoute: typeof ArtistaIdRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguidos': {
      id: '/seguidos'
      path: '/seguidos'
      fullPath: '/seguidos'
      preLoaderRoute: typeof SeguidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendaciones': {
      id: '/recomendaciones'
      path: '/recomendaciones'
      fullPath: '/recomendaciones'
      preLoaderRoute: typeof RecomendacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artista/$id': {
      id: '/artista/$id'
      path: '/artista/$id'
      fullPath: '/artista/$id'
      preLoaderRoute: typeof ArtistaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  BuscarRoute: BuscarRoute,
  FavoritosRoute: FavoritosRoute,
  RecomendacionesRoute: RecomendacionesRoute,
  SeguidosRoute: SeguidosRoute,
  WrappedRoute: WrappedRoute,
  AlbumIdRoute: AlbumIdRoute,
  ArtistaIdRoute: ArtistaIdRoute,
  PlaylistIdRoute: PlaylistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
